-- =============================================================================
-- Post-install: Initialize, resume, and verify compat dynamic tables
-- Runs after all compat DTs are created by other compat/*.sql files.
-- =============================================================================

-- Initialize DTs created with ON_SCHEDULE / DOWNSTREAM so they have data
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_AIRCRAFT_GROUND_SESSIONS REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_ADSB_GROUND_POINTS REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_GATE_TIME REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_UTIL_DAILY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_AIRLINE_DWELL_DAILY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_DWELL_WITH_AIRLINE REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_DAILY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_HOURLY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRACKER_FLIGHT_LIST REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_TRAFFIC_DAILY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_DELAY_DAILY REFRESH;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.RUNWAY_CROSSINGS_DETAILED REFRESH;

-- Resume incremental refresh
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_AIRCRAFT_GROUND_SESSIONS RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_ADSB_GROUND_POINTS RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_GATE_TIME RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_UTIL_DAILY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_AIRLINE_DWELL_DAILY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_DWELL_WITH_AIRLINE RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_DAILY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_HOURLY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRACKER_FLIGHT_LIST RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_TRAFFIC_DAILY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_DELAY_DAILY RESUME;
ALTER DYNAMIC TABLE ${DATABASE}.${SCHEMA}.RUNWAY_CROSSINGS_DETAILED RESUME;

-- Verify compat DTs are queryable
SELECT 'GATE_ANALYSIS_ADSB_GROUND_POINTS' AS tbl, COUNT(*) AS cnt FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_ADSB_GROUND_POINTS
UNION ALL SELECT 'GATE_ANALYSIS_AIRCRAFT_GROUND_SESSIONS', COUNT(*) FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_AIRCRAFT_GROUND_SESSIONS
UNION ALL SELECT 'GATE_ANALYSIS_FLIGHT_GATE_TIME', COUNT(*) FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_GATE_TIME
UNION ALL SELECT 'GATE_ANALYSIS_GATE_UTIL_DAILY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_UTIL_DAILY
UNION ALL SELECT 'GATE_ANALYSIS_GATE_AIRLINE_DWELL_DAILY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_GATE_AIRLINE_DWELL_DAILY
UNION ALL SELECT 'GATE_ANALYSIS_FLIGHT_DWELL_WITH_AIRLINE', COUNT(*) FROM ${DATABASE}.${SCHEMA}.GATE_ANALYSIS_FLIGHT_DWELL_WITH_AIRLINE
UNION ALL SELECT 'FLIGHT_TRAFFIC_FACT_ADSB_DAILY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_DAILY
UNION ALL SELECT 'FLIGHT_TRAFFIC_FACT_ADSB_HOURLY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_ADSB_HOURLY
UNION ALL SELECT 'FLIGHT_TRACKER_FLIGHT_LIST', COUNT(*) FROM ${DATABASE}.${SCHEMA}.FLIGHT_TRACKER_FLIGHT_LIST
UNION ALL SELECT 'FLIGHT_TRAFFIC_FACT_AIRLINE_TRAFFIC_DAILY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_TRAFFIC_DAILY
UNION ALL SELECT 'FLIGHT_TRAFFIC_FACT_AIRLINE_DELAY_DAILY', COUNT(*) FROM ${DATABASE}.${SCHEMA}.FLIGHT_TRAFFIC_FACT_AIRLINE_DELAY_DAILY
UNION ALL SELECT 'RUNWAY_CROSSINGS_DETAILED', COUNT(*) FROM ${DATABASE}.${SCHEMA}.RUNWAY_CROSSINGS_DETAILED;
