-- =============================================================================
-- Policy Pack: Airport Default Thresholds
--
-- This file documents the standard airport thresholds. The actual seeding
-- is done by the airport adapter (adapters/airport/03_seed_policy.sql).
--
-- To customize for a specific airport, UPDATE the POLICY row after install:
--
--   UPDATE <DB>.DWELL_CORE.POLICY
--   SET ground_altitude_max_ft = 75,     -- noisier altimeter at high-elevation airports
--       zone_assign_radius_m   = 80      -- tighter gate spacing
--   WHERE site_id = (SELECT site_id FROM <DB>.DWELL_CORE.SITE LIMIT 1);
--
-- =============================================================================
-- Standard airport defaults:
--
-- | Parameter               | Value | Unit    | Rationale                                      |
-- |-------------------------|-------|---------|-------------------------------------------------|
-- | ground_altitude_max_ft  | 50    | feet    | ADS-B barometric altitude on ground is ≤50 ft   |
-- | ground_speed_max_kts    | 40    | knots   | Taxiing speed; above = likely airborne          |
-- | session_gap_minutes     | 20    | minutes | Gap that splits a ground session                |
-- | facility_radius_m       | 5000  | meters  | "Near airport" radius for relevance filtering   |
-- | zone_assign_radius_m    | 120   | meters  | Max distance to assign a point to a gate         |
-- =============================================================================
