-- drop-order.sql
-- Complete DROP statements in dependency-safe order.
-- Replace {TARGET_DB} with specific airport database (e.g., AIRPORT_SAN) or loop over all.
-- Always run in DRY_RUN mode first (review output before executing).

-- ============================================================
-- PHASE 1: Streamlit Apps
-- ============================================================
-- Drop dashboard app (if hosted in a separate DB, adjust accordingly)
DROP STREAMLIT IF EXISTS AVIA_INSTALLER.PUBLIC.AIRPORT_ANALYTICS_DASHBOARD;

-- ============================================================
-- PHASE 2: Tasks (suspend leaf-to-root, then drop root-to-leaf)
-- ============================================================
ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_REFRESH_ANALYTICS SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_REFRESH_ANALYTICS;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_REFRESH_DERIVED SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_REFRESH_DERIVED;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_FLIGHT_SCHEDULE SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_FLIGHT_SCHEDULE;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ENRICH_ADSB SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ENRICH_ADSB;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ENRICH_AIRCRAFT_META SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ENRICH_AIRCRAFT_META;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ADSB_BACKFILL_ONCE SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ADSB_BACKFILL_ONCE;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ADSB_BACKFILL_RETRY SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_ADSB_BACKFILL_RETRY;

ALTER TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_INGEST_ADSB SUSPEND;
DROP TASK IF EXISTS {TARGET_DB}.PUBLIC.TASK_INGEST_ADSB;

-- ============================================================
-- PHASE 3: Dynamic Tables (leaf to root)
-- ============================================================
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_TRAFFIC_FACT_AIRLINE_DELAY_DAILY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_TRAFFIC_FACT_AIRLINE_TRAFFIC_DAILY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_TRACKER_FLIGHT_LIST;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_TRAFFIC_FACT_ADSB_HOURLY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_TRAFFIC_FACT_ADSB_DAILY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.RUNWAY_CROSSINGS_DETAILED;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_FLIGHT_DWELL_WITH_AIRLINE;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_GATE_AIRLINE_DWELL_DAILY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_GATE_UTIL_DAILY;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_FLIGHT_GATE_TIME;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_ADSB_GROUND_POINTS;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.GATE_ANALYSIS_AIRCRAFT_GROUND_SESSIONS;
DROP DYNAMIC TABLE IF EXISTS {TARGET_DB}.PUBLIC.ADSB_DATA_LOCAL;

-- ============================================================
-- PHASE 4: Views
-- ============================================================
DROP VIEW IF EXISTS {TARGET_DB}.PUBLIC.HELPER_LANDING_LIVE_TIMETABLE;
DROP VIEW IF EXISTS {TARGET_DB}.PUBLIC.V_AIR_OPS_TIMELINE;
DROP VIEW IF EXISTS {TARGET_DB}.PUBLIC.V_AIR_OPS_DAILY_KPIS;

-- ============================================================
-- PHASE 5: Stored Procedures
-- ============================================================
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_REFRESH_ANALYTICS();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_REFRESH_DERIVED();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_SMOKE_CHECK(STRING);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_RESUME_OPTIONAL_TASK(STRING);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_FLIGHT_SCHEDULE_INGEST_AND_ETL();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_BACKFILL_FLIGHT_SCHEDULE_WINDOW(INT, INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_BACKFILL_FLIGHT_SCHEDULE(INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ETL_SCHEDULE_TO_FLIGHT_SCHEDULE();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_INGEST_FLIGHT_SCHEDULE(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_START_BACKFILL_RETRY_UTC();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_RUN_BACKFILL_RETRY_UTC();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_START_BACKFILL_HISTORY();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_RUN_BACKFILL_ONCE();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_BACKFILL_ADSB_HISTORY();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_PROCESS_FROM_STAGE(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_CLEANUP_STAGE(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_FILTER_AND_INSERT_SQL(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_LOAD_NDJSON_TO_INTERIM(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_EXTRACT_TO_NDJSON(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_DOWNLOAD_TO_STAGE(VARCHAR);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ENRICH_AIRCRAFT_META_AND_BACKFILL();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_BACKFILL_ADSB_AIRCRAFT_DESC(INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ENRICH_AIRCRAFT_META(INT, INT, INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_DEDUP_ADSB_DATA(INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ADSB_INGEST_AND_ETL();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ETL_ADSB_TO_DATA(INT);
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_INGEST_ADSB_REALTIME();
DROP PROCEDURE IF EXISTS {TARGET_DB}.PUBLIC.PROC_ENRICH_ADSB_WITH_SCHEDULE(INT);

-- ============================================================
-- PHASE 6: Functions / UDFs
-- ============================================================
DROP FUNCTION IF EXISTS {TARGET_DB}.PUBLIC.UDF_TZID_FROM_LATLON(DOUBLE, DOUBLE);
DROP FUNCTION IF EXISTS {TARGET_DB}.PUBLIC.GET_OSM_TAG(VARIANT, STRING);
DROP FUNCTION IF EXISTS {TARGET_DB}.PUBLIC.ST_GETPOLYGONS(OBJECT);

-- ============================================================
-- PHASE 7: Tables (Gold/Silver/Bronze/Helper)
-- ============================================================
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.H2H_CONFLICT_PAIRS;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_INGEST_AUDIT;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_QA_COUNTS_DAILY;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_MONITOR_LAST_REFRESH;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_INSTALL_AUDIT;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_ADSB_HISTORY_INTERIM;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_ADSB_BACKFILL_STATUS;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_RECURRING_CALLSIGN_PRIOR;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_FLIGHT_MATCH_RESULT;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_FLIGHT_MATCH_CANDIDATES;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_FLIGHT_LEG;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.ADSB_DATA;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.FLIGHT_SCHEDULE;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_FLIGHT_SCHEDULE_RAW;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_AIRCRAFT_META;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_ADSB_LOL_RAW;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_AIRLINE_IATA_ICAO_MAP;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.HELPER_AIRLINE_DIM;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.PROPERTIES_RUNWAYS;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.PROPERTIES_GATES;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.PROPERTIES_INFRASTRUCTURE;
DROP TABLE IF EXISTS {TARGET_DB}.PUBLIC.PROPERTIES_AIRPORT;

-- ============================================================
-- PHASE 8: Stages and File Formats
-- ============================================================
DROP STAGE IF EXISTS {TARGET_DB}.PUBLIC.ADSB_HISTORY_STAGE;
DROP FILE FORMAT IF EXISTS {TARGET_DB}.PUBLIC.FF_AIRLINES_CSV;

-- ============================================================
-- PHASE 9: Secrets
-- ============================================================
DROP SECRET IF EXISTS {TARGET_DB}.PUBLIC.aviationstack_key;

-- ============================================================
-- PHASE 10: External Access Integrations (account-level)
-- ============================================================
-- Note: EAI names are derived from {TARGET_DB}_PUBLIC_*
-- Example for AIRPORT_SAN:
DROP INTEGRATION IF EXISTS AIRPORT_SAN_PUBLIC_AVIATIONSTACK_EAI;
DROP INTEGRATION IF EXISTS AIRPORT_SAN_PUBLIC_GITHUB_EAI;
DROP INTEGRATION IF EXISTS AIRPORT_SAN_PUBLIC_ADSB_LOL_EAI;
DROP INTEGRATION IF EXISTS AIRPORT_SAN_PUBLIC_PYPI_ACCESS_INTEGRATION;

-- ============================================================
-- PHASE 11: Network Rules (inside airport database)
-- ============================================================
DROP NETWORK RULE IF EXISTS {TARGET_DB}.PUBLIC.PUBLIC_AVIATIONSTACK_RULE;
DROP NETWORK RULE IF EXISTS {TARGET_DB}.PUBLIC.PUBLIC_GITHUB_RULE;
DROP NETWORK RULE IF EXISTS {TARGET_DB}.PUBLIC.PUBLIC_ADSB_LOL_RULE;
DROP NETWORK RULE IF EXISTS {TARGET_DB}.PUBLIC.PUBLIC_PYPI_NETWORK_RULE;

-- ============================================================
-- PHASE 12: Tags
-- ============================================================
DROP TAG IF EXISTS {TARGET_DB}.TAGS.COMPONENT;
DROP TAG IF EXISTS {TARGET_DB}.TAGS.SOLUTION;

-- ============================================================
-- PHASE 13: Schemas and Database (CASCADE cleans up any stragglers)
-- ============================================================
DROP SCHEMA IF EXISTS {TARGET_DB}.TAGS CASCADE;
DROP DATABASE IF EXISTS {TARGET_DB} CASCADE;
